### ISSUE TITLE
NameError: name 'ModelCheckpoint' is not defined

### ISSUE THREAD

**Issue by Ahme1994** [bdsaglam/torch-scae#4] opened 2020-06-08 05:01 UTC
hello sir 
when I converted the train file to pytorch I got this problem 
if 'save_top_k' in training_params:
            checkpoint_callback = ModelCheckpoint(
            save_top_k=training_params['save_top_k'])
            training_params.update(checkpoint_callback=checkpoint_callback)
            del training_params['save_top_k']
        trainer = trainer(**training_params)
        trainer.fit(model)   
in this loop sometimes the error is 
 parser = Trainer.add_argparse_args(parser)
NameError: name 'Trainer' is not defined

**Comment by bdsaglam** [comment] 2020-06-08 08:12
Hi, I think you have some problems about installation. You need to install this repository with pip as usual. I am closing this issue since the problem is not specific to the repo.

**Closed by bdsaglam** 2020-06-08 08:12 UTC
